---
title: "Data Project "
description: |
  Predicting House Prices using R 
author:
  - name: I found this regression anaysis on Kaggle, written by Pradeep Tripathi 
    url: "https://www.kaggle.com/pradeeptripathi/predicting-house-prices-using-r"

date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Data Set: 

My Goal: 

library(caret)
library(ggplot2)

Really!  I'm lost so I'm switching to an easier data set.  
Abalone is what another student is working on so I'm going to try to look at this data set: 

ABALONE:  a marine snail.  You can read about it here in Wikipedia!  

Great, I'm looking at house prices and then  I am changing to snails. 
url: "https://en.wikipedia.org/wiki/Abalone" 

```{r,echo=TRUE}
#view the whole dataset
    # Read CSV data
    data_abalone <- read.csv("./abalone.csv", header=F)

```

```{r}
  # Clean NAs and empty values from dataset
    data_abalone[data_abalone==""] <- NA
    data_abalone <- na.omit(data_abalone)
```

