---
title: "Resume"
author: "Tracy Morgan"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{=tex}
\begin{center}


# Tracy L. Morgan, MBA, CPA


tplmorgan\@gmail.com  

101 E. Main Street Clinton, MS 39056

601-209-8496

\end{center}
```

------------------------------------------------------------------------

## Academic Employment

### Holmes Community College, Goodman, MS 2020 - present

Accounting and Business Instructor, Associate Department Chair for
Business and Accounting, Student Advisor

### Mississippi College, Clinton, MS August 2018 -- present

Adjunct Accounting and Business Faculty and Canvas Consultant for the
School of Business

### Mississippi Virtual Community College Instructor August 2011 -- present

Online Teacher for various MSVCC colleges: Hinds Community College,
Holmes Community Colege, Mississippi Gulf Cost Community College

### Pearson, Faculty Advisor, Hoboken, NJ July 2019 -- December 2020

National Trainer, Educational Consultant and Subject Matter Expert

### Hinds Community College, Full-time Instructor August 2010 - December 2017

Accounting and Business Instructor, Alpha Beta Gamma Advisor

## Education

### Mississippi State University, Starkville, MS

Currently enrolled in the Master of Taxation program -- August 2021 -
presen

### Jackson State Univsersity, Jackson, MS

Additional Graduate Work -- May 2013

### Mississippi College University, Clinton, MS

Additional Graduate Work -- August 2013

Masters in Business Administration -- May 1994

Master of Ars in Business Administration, Accounting Emphais -- May 1990

## Licenses and Certifications

CPA, State of Mississippi, License \# 4554

American Institute of CPAs

Mississippi Society of CPAs, Committee on Education

Completed the APPQM training, Quality Matters

## Technology in the Classroom

YouTube \| Snag-It \| ZOOM \| Camtasia \| Canvas \| Blackboard \| Moodle
\| Pearson MyLab \| CengageNow \| Cengage Mindtap \| McGraw Hill Connect
\| Campus Knot! \| Canvas Studio \| Kahoot! \| Padlet \|Microsoft Office
\| Salesforce

\#\#Courses Taught

Principles of Accounting I and II \| Accounting Survey \| Business
Statistics \| Personal Finance \| Legal Environment of Business \|
Inroduction to Business \| Introduction to Marketing \| Computer
Applications
